### PR TITLE
Rename ICEsat2_SI_tools Module to tools for PEP 8 Compliance

### PR DESCRIPTION
**Pull request by cpaniaguam**
This PR addresses the renaming of the `ICEsat2_SI_tools` module to `tools` in order to comply with PEP 8 naming conventions. PEP 8 recommends module names to be short, lowercase, and avoid underscores if possible.

## Changes

- Renamed `ICEsat2_SI_tools` module to `tools`
- Updated all import statements and references to use the new module name

### Files updated
Files in the old `ICEsat2_SI_tools` directory and relevant files in the `analysis_db` directory.
```
src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py
src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py
src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py
src/icesat2_tracks/analysis_db/B04_angle.py
src/icesat2_tracks/analysis_db/B05_define_angle.py
src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
src/icesat2_tracks/tools/__init__.py
src/icesat2_tracks/tools/angle_optimizer.py
src/icesat2_tracks/tools/beam_stats.py
src/icesat2_tracks/tools/convert_GPS_time.py
src/icesat2_tracks/tools/convert_julian.py
src/icesat2_tracks/tools/filter_regrid.py
src/icesat2_tracks/tools/generalized_FT.py
src/icesat2_tracks/tools/iotools.py
src/icesat2_tracks/tools/lanczos.py
src/icesat2_tracks/tools/read_ground_tracks.py
src/icesat2_tracks/tools/sliderule_converter_tools.py
src/icesat2_tracks/tools/spectral_estimates.py
src/icesat2_tracks/tools/spicke_remover.py
src/icesat2_tracks/tools/wave_tools.py
```

### CODE REVIEW

**Comment by kmilo9999** [comment]
Can we merge this PR after #132 ? 
That one has some changes in those files's code.

**Review by hollandjg — DISMISSED** [review]
Looks good to me!

**Comment by cpaniaguam** [comment]
> Can we merge this PR after #132 ? That one has some changes in those files's code.

Surely!

**Review by hollandjg — APPROVED** [review]
Great!

**Comment by cpaniaguam** [comment]
Completed in #189

**Pull request closed without merging**
